name: Luarocks

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches:
      - master
    tags: 
      - v*

  pull_request:
    branches:
      - master

# A workflow run jobs that will publish the rock on successful tests
jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: leafo/gh-actions-lua@v5
        with:
          luaVersion: "5.1.5"

      - uses: leafo/gh-actions-luarocks@v2
        with:
          luarocksVersion: "3.1.3"

      - name: Compile Lua code
        run: luarocks make

      - name: Run tests
        run: luarocks test

      - name: Run code analysis
        run: luacheck src spec

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./luacov.report.out
          flags: unittests
          fail_ci_if_error: true

  # Publish rocks
  publish:
    # Ensure test job passes before pushing .
    needs: test

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: leafo/gh-actions-lua@v5
        with:
          luaVersion: "5.1.5"

      - uses: leafo/gh-actions-luarocks@v2
        with:
          luarocksVersion: "3.1.3"

      - name: Publish rock
        run: |
          luarocks install lua-cjson
          rockspec=$(ls kong-plugin-opa-*.rockspec)
          luarocks upload $rockspec --api-key=${{ secrets.LUAROCKS_TOKEN }} --force
